#!/bin/bash

# the following are file types we strip C-style comments for:
strip_comment_suffixes=(
  "wgsl"
  "glsl"
)

infile="$1"
if [ -z "$infile" ]; then
  echo "Usage: $0 <filename> [namespace]" 2>&1
  exit 1
fi

if [ ! -f "$infile" ]; then
  echo "Resource compiler: File $infile not found." 2>&1
  exit 1
fi

outfile="$infile.h"

# don't update if outfile is newer than infile
if [ ! "$infile" -nt "$outfile" ]; then
  echo "Resource compiler: $outfile up to date"
  exit
fi

suffix=${infile##*.} # get the suffix
suffix=${suffix,,} # make it lowercase

# generate a fairly unique hash to act as a rawstring prefix/suffix
shorthash=$(md5sum "$infile" | cut -c 1-16)

if [ -z "$2" ]; then
  namespace=$(dirname "$infile" | sed 's/\//::/g')
else
  namespace="$2"
fi
resourcename=$(basename "$infile" | sed 's/\./_/g')

# truncate the destination file
> "$outfile"

# comments
echo "#pragma once"$'\n' >> "$outfile"
echo "// This file is automatically generated from $infile by $0"$'\n' >> "$outfile"

# optional namespace
if [ ! -z "$namespace" ]; then
  echo "namespace $namespace {"$'\n' >> "$outfile"
fi

# header
echo -n "inline constexpr char const *${resourcename}{R\"${shorthash}(" >> "$outfile"

# content
if printf '%s\0' "${strip_comment_suffixes[@]}" | grep -Fxzq -- "$suffix"; then
  # strip comments and whitespace-only lines
  sed "s/ *\/\/.*//;/^[ ]*$/d" "$infile" >> "$outfile"
else
  cat "$infile" >> "$outfile"
fi

# footer
echo ")${shorthash}\"};" >> "$outfile"

if [ ! -z "$namespace" ]; then
  echo $'\n'"} // namespace $namespace" >> "$outfile"
fi

echo "Resource compiler: $infile compiled to $outfile: $namespace::$resourcename"
